# Generated by Django 4.0.6 on 2022-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='taskID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
