name: "Abricos Deploy"
on: 
  push:
    branches:
      -master
jobs: 
  build-deploy: 
    name: build and deploy 
    runs-on: ubuntu-latest 
    steps: 
      - name: checkout 
        uses: actions/checkout@v3
        
      - name: connect_to_server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            touch  weare.txt
          
    
  
